services/frontend/package-lock.json
services/frontend/package.json
services/frontend/public/index.html

Added the material UI library for styling assistance.
The required icon font was loaded into the index.html folder inside the front-end service while the package for material itself was installed via npm.

CDHSH-Add material UI library

---

services/frontend/package-lock.json
services/frontend/package.json
services/frontend/src/App.js
services/frontend/src/App.scss
services/frontend/src/scenes/Landing/Landing.scss
services/frontend/src/scenes/Landing/LandingLayout.js
services/frontend/src/scenes/SignUp/SignUp.js
services/frontend/src/scenes/SignUp/SignUp.scss
services/frontend/src/scenes/SignUp/SignUpLayout.js
services/frontend/src/scenes/SignUp/index.js
services/frontend/src/scenes/index.js
services/frontend/src/styles/_colors.scss
services/frontend/src/styles/_mixins.scss
services/frontend/src/utils/screenUrls.js

Changelog:
- The layout of the Sign Up page has been created.
- Users can now click the "Sign Up" buttons on the Landing page to visit the Sign Up page.
Implementation Details:
- Setup the Material UI theme to use our colors.
- Converted the buttons on the Landing page to use react-router `Link`s for navigation.
- Created the ScreenUrls constant for holding all of the screen.. urls.

CDHSH-50 Created the layout for the Sign Up page and linked to it from the Landing page.

---

services/backend/src/db/seedData.js
services/backend/src/db/seeders/20190531092452-create-default-users.js
services/frontend/src/AppRouter.js
services/frontend/src/components/Navbar/Navbar.js
services/frontend/src/components/Navbar/Navbar.scss
services/frontend/src/components/Navbar/NavbarLayout.js
services/frontend/src/components/Navbar/connect.js
services/frontend/src/scenes/Landing/Landing.scss
services/frontend/src/store/sagas/auth.sagas.js
services/frontend/src/store/slices/auth.slice.js
services/frontend/src/styles/_dimens.scss

Changelog:
- Users can now log out from the application.
- Logging in now causes users to go directly to their profile page.
- Setup a seeder for creating a default user.
- Modified the Landing page's header's height to be the same as the app's navbar.
- Decreased the app's navbar height slightly to better balance the height between the landing header and the navbar.

CDHSH-61 Implemented the logout functionality.

---

services/backend/src/components/profiles/profiles.hooks.js
services/backend/src/db/seedData.js
services/backend/src/db/seeders/20190603191615-create-default-profile.js

Changelog:
- Added new seed file to the backend which holds dummy data for the profile.
- Added the authentication hook to the profile table to ensure that the user is authenticated before accessing data.
- Generated a seedfile using sequalize and added dummy data to the file seedData.js

CDHSH-70 Added seed file for profile

---

services/frontend/.eslintrc
services/frontend/public/index.html
services/frontend/src/App.scss
services/frontend/src/AppRouter.js
services/frontend/src/scenes/Projects/Projects.js
services/frontend/src/scenes/Projects/Projects.scss
services/frontend/src/scenes/Projects/ProjectsLayout.js
services/frontend/src/scenes/Projects/index.js
services/frontend/src/scenes/index.js
services/frontend/src/styles/_colors.scss
services/frontend/src/utils/models/Project.js
services/frontend/src/utils/models/index.js

Changelog:
- Users can now properly navigate to the Projects list page to view some dummy data.
- The Projects list page now has functional filters for all, active, or inactive projects.
- Users can now see "Skillhub" in the title of their browser tab when using the app.
- Fixed `$color-neutral-8`; it was missing a letter before.
- Enabled an eslint rule for ensuring spaces around the arrow in an arrow function are enforced.

CDHSH-69 Created the base layout for the Projects list page.

---

services/backend/src/db/seedData.js
services/backend/src/db/seeders/20190605105124-create-default-skills.js
services/backend/src/db/seeders/20190605105126-create-default-projects.js
services/backend/src/db/seeders/20190605105228-create-default-project-skills.js

Changelog:
- N/A
- Created seeders for projects and skills data.

CDHSH-74 Created the seed data and seeders to setup some dummy projects/skills.

---

services/backend/src/components/projects/projects.hooks.js
services/backend/src/components/skills/skills.hooks.js
services/frontend/src/scenes/Projects/Projects.js
services/frontend/src/scenes/Projects/connect.js
services/frontend/src/store/crossSliceSelectors.js
services/frontend/src/store/mountpoints.js
services/frontend/src/store/sagas/app.sagas.js
services/frontend/src/store/sagas/index.js
services/frontend/src/store/sagas/projects.sagas.js
services/frontend/src/store/sagas/skills.sagas.js
services/frontend/src/store/slices/index.js
services/frontend/src/store/slices/projects.slice.js
services/frontend/src/store/slices/skills.slice.js
services/frontend/src/utils/models/Project.js
services/frontend/src/utils/models/Project.test.js
services/frontend/src/utils/models/Skill.js
services/frontend/src/utils/models/Skill.test.js
services/frontend/src/utils/models/index.js

Changelog:
- Users can now see live data on the Projects list page.
- Added authentication to the projects and skills Feathers services.
- Created the projects and skills store slices.
- Created the app boot process that runs on login or page reload.
- Refactored and wrote tests for some existing projects related logic.

CDHSH-73 Connected the Projects list scene to the store/backend for live data.

---

services/frontend/src/store/mountpoints.js
services/frontend/src/store/sagas/app.sagas.js
services/frontend/src/store/sagas/index.js
services/frontend/src/store/sagas/profiles.sagas.js
services/frontend/src/store/sagas/projects.sagas.js
services/frontend/src/store/slices/index.js
services/frontend/src/store/slices/profiles.slice.js
services/frontend/src/utils/models/Profile.js
services/frontend/src/utils/models/index.js

Changelog:
- Added functionality to fetch all the profile data and add it to the redux store, stored by ID.
- Created a new profile saga, slice, mountpoint and request slice.
- Added profilemodel to more easily normalize data.

CDHSH-71 Load profile seed data into the redux store

---

services/frontend/src/components/Navbar/Navbar.js
services/frontend/src/components/Navbar/NavbarLayout.js
services/frontend/src/components/Navbar/connect.js

Changelog:
- Users can now see that the highlighted navbar tab is always correct.
- N/A

CDHSH-72 Fixed the Navbar to have the active tab state derived from the URL, instead of just from internal component state.

---

services/frontend/src/components/ProjectCard/ProjectCard.js
services/frontend/src/components/ProjectCard/ProjectCard.scss
services/frontend/src/components/ProjectCard/index.js
services/frontend/src/components/index.js
services/frontend/src/scenes/Profile/Profile.js
services/frontend/src/scenes/Profile/Profile.scss
services/frontend/src/scenes/Profile/ProfileLayout.js
services/frontend/src/scenes/Projects/Projects.scss
services/frontend/src/scenes/Projects/ProjectsLayout.js

Changelog:
- Users can now see dummy projects on their personal profile page. 
- Refactored the ProjectCard (and related components) into its own file.

CDHSH-77 Created the layout for the Projects section of the Profile scene.

---

services/frontend/src/components/Navbar/Navbar.scss
services/frontend/src/components/Navbar/NavbarLayout.js
services/frontend/src/scenes/Profile/Profile.js
services/frontend/src/scenes/Profile/Profile.scss
services/frontend/src/scenes/Profile/ProfileLayout.js
services/frontend/src/scenes/Profile/connect.js
services/frontend/src/store/crossSliceSelectors.js
services/frontend/src/store/sagas/auth.sagas.js
services/frontend/src/store/slices/profiles.slice.js
services/frontend/src/store/slices/user.slice.js
services/frontend/src/utils/models/Profile.js
services/frontend/src/utils/models/Profile.test.js
services/frontend/src/utils/models/User.js

Changelog:
- Loaded data from the store into the view
- Changed brand logo in navbar to use material-ui hovering/clicking
Other implementation details:
- Added selectors for `userId` and `profilebyId`
- Mapped data from the store onto the props and loaded inside the layout
- Added function to take the first letter of names (for the avatar)
- Fixed routing from landing page going to /app
- Added tests for new functions inside of profile model

CDHSH-75 Load data form the redux store into the frontend view

---

services/frontend/src/components/ProjectCard/ProjectCard.js
services/frontend/src/components/ProjectCard/ProjectCard.scss
services/frontend/src/components/ScrollContainer/ScrollContainer.scss
services/frontend/src/components/SkillsBadges/SkillBadges.js
services/frontend/src/components/SkillsBadges/SkillBadges.scss
services/frontend/src/components/SkillsBadges/index.js
services/frontend/src/components/TextBadge/TextBadge.js
services/frontend/src/components/TextBadge/TextBadge.scss
services/frontend/src/components/TextBadge/index.js
services/frontend/src/components/index.js
services/frontend/src/scenes/Profile/Profile.js
services/frontend/src/scenes/Profile/Profile.scss
services/frontend/src/scenes/Profile/ProfileLayout.js
services/frontend/src/utils/models/Project.js
services/frontend/src/utils/models/Project.test.js

Changelog:
- Added skills view to the profile
- Fixed sticky sidebar not being sticky
- Added loading indicator to entire profile page
Other implementation details:
- Moved skills to a separate component
- Added `CircularProgress` spinner for loading to the main content area (previously in sections)
- Changed `MergeWithSkills` to output an array of objects instead of skill strings.
- Changed project cards on the profile to render with useMemo

CDHSH-80 created a component to view skills data on the profile page

---

services/backend/src/components/profiles/profiles.hooks.js
services/backend/src/db/seedData.js
services/backend/src/db/seeders/20190611193802-create-default-profile-skills.js

Changelog:
- Added seed data to backend
Implementation Details:
- Created `profileSkills` seeder and seed data
- Added `includeSkills()` hook to populate the profile.

CDHSH-82 Created seed data for profileSkills and implemented skills hook

---

services/frontend/src/components/SkillsBadges/SkillBadges.js
services/frontend/src/scenes/ProjectDetails/ProjectDetails.scss
services/frontend/src/scenes/ProjectDetails/ProjectDetailsLayout.js
services/frontend/src/store/crossSliceSelectors.js

Changelog:
• Added skills view to project details page
• Refactored Project Details

CDHSH-64 implemented skills view for project details page

---

services/frontend/src/components/PersonalDetailsDialog/PersonalDetailsDialog.js
services/frontend/src/components/PersonalDetailsDialog/PersonalDetailsDialog.scss
services/frontend/src/components/PersonalDetailsDialog/index.js
services/frontend/src/components/PersonalDetailsForm/PersonalDetailsForm.js
services/frontend/src/components/PersonalDetailsForm/PersonalDetailsForm.scss
services/frontend/src/components/PersonalDetailsForm/index.js
services/frontend/src/components/index.js
services/frontend/src/scenes/Profile/Profile.scss
services/frontend/src/scenes/Profile/ProfileLayout.js

Changelog:
- Added dialog to edit the personal details on the profile page
Implementation Details:
- Created controlled components to easily compile data for updating

CDHSH-87 Added frontend edit dialog for personal details on the profile

---

services/frontend/src/scenes/ProjectDetails/ProjectDetailsLayout.js

Changelog:
• Added onClick for contributors on project page

CDHSH-98 Added on click redirection to profile for each contributors

---

services/frontend/package-lock.json
services/frontend/package.json
services/frontend/src/components/EditSkillsDialog/EditSkillsDialog.js
services/frontend/src/components/EditSkillsDialog/EditSkillsDialog.scss
services/frontend/src/components/EditSkillsDialog/index.js
services/frontend/src/components/index.js
services/frontend/src/scenes/Profile/Profile.js
services/frontend/src/scenes/Profile/Profile.scss
services/frontend/src/scenes/Profile/ProfileLayout.js
services/frontend/src/scenes/Profile/connect.js
services/frontend/src/utils/models/Profile.js
services/frontend/src/utils/models/Profile.test.js

Changelog:
• Added frontend for dialog to edit the skills on the profile page
Implementation Details
• material-ui-chip-input being used to handle the inputs

CDHSH-90 Added frontend for EditSkills Dialog

---

services/frontend/src/scenes/ProjectDetails/ProjectDetails.js
services/frontend/src/scenes/ProjectDetails/ProjectDetails.scss
services/frontend/src/scenes/ProjectDetails/ProjectDetailsLayout.js

Changelog
• Added contributor sorting and fixed scss

CDHSH-100 Added contributor sorting and fixed scss

---

services/backend/src/components/profiles/profiles.hooks.js

Changelog
• Added query customizer for findOrCreate for profile

CDHSH-106 Added query customizer for findOrCreate

---

services/backend/.eslintrc
services/backend/src/utils/models/Project.js
services/frontend/.eslintrc
services/frontend/src/components/LoadingValidator/LoadingValidator.js
services/frontend/src/scenes/ProjectDetails/connect.js
services/frontend/src/store/sagas/profiles.sagas.js
services/frontend/src/store/sagas/projects.sagas.js
services/frontend/src/utils/models/Project.js
services/scraper/.eslintrc
services/scraper/Dockerfile
services/scraper/scripts/skill_file_breakdown.rb
services/scraper/src/components/scraper/scraperController.js
services/scraper/src/config.js
services/scraper/src/scrapers/GitScraper.js
services/scraper/src/scrapers/SkillhubBridge.js
services/scraper/src/scrapers/index.js
services/scraper/src/utils/index.js
services/scraper/src/utils/loggerUtils.js

Changelog:
- Scraper can now handle scraping a list of repos from a (Github) organization, cloning the repos, and then parsing them for raw stats related to skills.
- The Scraper Dockerfile has been updated to include ruby so that we can leverage the github-linguist package.
- Added the 'brace-style' eslint rule to enforce if-else styling (and fixed any existing violations). 
Reviewer Notes:
- Note that the skills scraping is currently setup on a test route and is not yet connected to the Backend; that is a separate ticket.

CDHSH-110 Modified the Scraper to clone and parse repos.

---

services/frontend/src/scenes/ProjectDetails/ProjectDetails.js
services/frontend/src/scenes/ProjectDetails/ProjectDetails.scss
services/frontend/src/scenes/ProjectDetails/ProjectDetailsLayout.js
services/frontend/src/scenes/ProjectDetails/connect.js
services/frontend/src/store/crossSliceSelectors.js
services/frontend/src/store/sagas/projectChangeRecords.sagas.js
services/frontend/src/store/slices/projectChangeRecords.slice.js
services/frontend/src/utils/helperFunctions.js
services/frontend/src/utils/models/ProjectChangeRecord.js

Changelog:
- Added changelogs to the project details section.
- Created selector for `projectChangeLogs` by `projectId`
- hooked up `projectChangeRecords` similarly to `projectProfiles`, `profileSkills`, etc...

CDHSH-65 added redux normalization and changelogs to project page

---

services/frontend/package-lock.json
services/frontend/package.json
services/frontend/src/index.js

Changelog: 
- Added poly filling package `react-app-polyfill`  to support internet explorer.
N/A

CDHSH-109 Added react-app-polyfill to provide ie11 support

---

services/backend/src/components/projects/projects.hooks.js
services/frontend/src/components/AvatarIcon/AvatarIcon.js
services/frontend/src/components/RoleInputDialog/RoleInputDialog.js
services/frontend/src/components/RoleInputDialog/RoleInputDialog.scss
services/frontend/src/components/RoleInputDialog/index.js
services/frontend/src/components/index.js
services/frontend/src/scenes/Profile/components/Projects/Projects.js
services/frontend/src/scenes/Profile/components/Projects/Projects.scss
services/frontend/src/scenes/Profile/components/Projects/connect.js
services/frontend/src/scenes/ProjectDetails/ProjectDetails.js
services/frontend/src/scenes/ProjectDetails/ProjectDetails.scss
services/frontend/src/scenes/ProjectDetails/ProjectDetailsLayout.js
services/frontend/src/scenes/ProjectDetails/components/ProjectInfo/ProjectInfo.js
services/frontend/src/scenes/ProjectDetails/components/ProjectInfo/ProjectInfo.scss
services/frontend/src/scenes/ProjectDetails/components/ProjectInfo/connect.js
services/frontend/src/scenes/ProjectDetails/connect.js
services/frontend/src/scenes/Search/SearchLayout.js
services/frontend/src/store/mountpoints.js
services/frontend/src/store/sagas/app.sagas.js
services/frontend/src/store/sagas/index.js
services/frontend/src/store/sagas/projects.sagas.js
services/frontend/src/store/sagas/user.sagas.js
services/frontend/src/store/sagas/users.sagas.js
services/frontend/src/store/slices/index.js
services/frontend/src/store/slices/user.slice.js
services/frontend/src/utils/models/User.js
services/frontend/src/utils/searchGlobals.js

Changelog:
- Added dialog to add a project to your profile with an inputted role
- Added to the changelog to show which user made changes
- Added changelog for adding yourself as a contributor
Other Implementation Details: 
- Reverted contributors section on project details page to have correct spacing.
- Capitalized some text (serach page prev/next and skill/name)
- Moved `RoleInputDialog` to seperate component for reuse
- Implemented `users` and `usersRequestsSlice` for loading in all users.

CDHSH-34 Implemented add project and fixed changelogs to include user.

---

services/backend/src/components/profiles/profiles.hooks.js
services/backend/src/components/scraperBridge/scraperBridge.service.js
services/backend/src/components/skills/skills.hooks.js
services/backend/src/externalServices/predictionsService.js
services/frontend/src/scenes/Search/Search.scss
services/predictions/src/predictors/skills_predictor.py
services/predictions/src/utils/email_matcher.py
services/scraper/src/scrapers/SkillhubBridge.js

Changelog:
- Connected the Scraper, the Predictions service, and the Backend all together to import repos from Github.
- Fixed a flex-shrink issue with the People cards on the Search page.

CDHSH-112 Connected the Scraper, the Predictions service, and the Backend all together to import repos from Github.

---

services/backend/src/components/projects/projects.hooks.js

Changelog:
- 'lastActive' times are now automatically updated each time the Scraper runs.
- N/A

CDHSH-107 Added a project hook to handle updating the lastActive time from the Scraper.

---

services/backend/src/components/users/users.hooks.js
services/backend/src/middleware/CustomVerifier.js
services/backend/src/middleware/authentication.js
services/backend/src/middleware/customVerifier.js
services/frontend/src/components/ProfileCard/ProfileCard.scss
services/frontend/src/components/ProjectCard/ProjectCard.scss
services/frontend/src/scenes/Landing/Landing.scss
services/frontend/src/scenes/Profile/components/Projects/Projects.js
services/frontend/src/scenes/Profile/components/Projects/Projects.scss
services/frontend/src/scenes/ProjectDetails/components/ProjectInfo/ProjectInfo.scss
services/frontend/src/scenes/Search/Search.scss
services/frontend/src/store/sagas/auth.sagas.js
services/frontend/src/styles/_dimens.scss

Changelog:
- Added pagination to the `searchDialog` as part of adding a project on your profile.
- Changed username (email) to be case insensitive and prevented new accounts via case sensitive entry.
- Increased the size of the project cards to match the profile cards
- Fixed visual bugs in chrome on the main profile page
- Fixed an auth saga not catching an error and therefore freezing up the application.
- Added a custom verifier for feathers authentication that is identical except for using `$iLike` for case insensitivity on the username.
- Changed some mobile responsiveness to be consistent across pages.

CDHSH-123 Implemented suggestions, added pagination and fixed chrome bugs.

---

services/frontend/src/scenes/Profile/components/Projects/Projects.js

Changelog:
- Changed filtering to only filter by active projects on the `My Profile` page.
Other implementation details:
- N/A

HOTFIX: Removed activity filtering from non-logged in users on profile pages
